server:
  port: ${PORT:8762}

spring:
  application:
    name: containerized-gateway


zuul:
  routes:
    containerized-main:
      path: /service1/**
      serviceId: containerized-service1
    containerized-accounts:
      path: /service2/**
      serviceId: containerized-service2
    containerized-auth:
      path: /auth-service/**
      serviceId: auth-service
  ribbon:
    ConnectTimeout: 120000
    ReadTimeout: 120000
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  