//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.14 at 07:53:51 PM CEST 
//


package auth.service.authservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for additionalServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="additionalServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parking" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="WiFi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Breakfast" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fullPansion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="halfPansion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AllInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="TV" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Kitchen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="privateBath" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "additionalServices", propOrder = {
    "parking",
    "wiFi",
    "breakfast",
    "fullPansion",
    "halfPansion",
    "allInclusive",
    "pet",
    "tv",
    "kitchen",
    "privateBath"
})
public class AdditionalServices {

    protected boolean parking;
    @XmlElement(name = "WiFi")
    protected boolean wiFi;
    @XmlElement(name = "Breakfast")
    protected boolean breakfast;
    protected boolean fullPansion;
    protected boolean halfPansion;
    @XmlElement(name = "AllInclusive")
    protected boolean allInclusive;
    protected boolean pet;
    @XmlElement(name = "TV")
    protected boolean tv;
    @XmlElement(name = "Kitchen")
    protected boolean kitchen;
    protected boolean privateBath;

    /**
     * Gets the value of the parking property.
     * 
     */
    public boolean isParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     */
    public void setParking(boolean value) {
        this.parking = value;
    }

    /**
     * Gets the value of the wiFi property.
     * 
     */
    public boolean isWiFi() {
        return wiFi;
    }

    /**
     * Sets the value of the wiFi property.
     * 
     */
    public void setWiFi(boolean value) {
        this.wiFi = value;
    }

    /**
     * Gets the value of the breakfast property.
     * 
     */
    public boolean isBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     * 
     */
    public void setBreakfast(boolean value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the fullPansion property.
     * 
     */
    public boolean isFullPansion() {
        return fullPansion;
    }

    /**
     * Sets the value of the fullPansion property.
     * 
     */
    public void setFullPansion(boolean value) {
        this.fullPansion = value;
    }

    /**
     * Gets the value of the halfPansion property.
     * 
     */
    public boolean isHalfPansion() {
        return halfPansion;
    }

    /**
     * Sets the value of the halfPansion property.
     * 
     */
    public void setHalfPansion(boolean value) {
        this.halfPansion = value;
    }

    /**
     * Gets the value of the allInclusive property.
     * 
     */
    public boolean isAllInclusive() {
        return allInclusive;
    }

    /**
     * Sets the value of the allInclusive property.
     * 
     */
    public void setAllInclusive(boolean value) {
        this.allInclusive = value;
    }

    /**
     * Gets the value of the pet property.
     * 
     */
    public boolean isPet() {
        return pet;
    }

    /**
     * Sets the value of the pet property.
     * 
     */
    public void setPet(boolean value) {
        this.pet = value;
    }

    /**
     * Gets the value of the tv property.
     * 
     */
    public boolean isTV() {
        return tv;
    }

    /**
     * Sets the value of the tv property.
     * 
     */
    public void setTV(boolean value) {
        this.tv = value;
    }

    /**
     * Gets the value of the kitchen property.
     * 
     */
    public boolean isKitchen() {
        return kitchen;
    }

    /**
     * Sets the value of the kitchen property.
     * 
     */
    public void setKitchen(boolean value) {
        this.kitchen = value;
    }

    /**
     * Gets the value of the privateBath property.
     * 
     */
    public boolean isPrivateBath() {
        return privateBath;
    }

    /**
     * Sets the value of the privateBath property.
     * 
     */
    public void setPrivateBath(boolean value) {
        this.privateBath = value;
    }

}
