//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.14 at 07:53:51 PM CEST 
//


package auth.service.authservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for pricePerMonth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pricePerMonth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Januar" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Februar" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="March" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="April" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="May" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="June" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="July" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="August" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="September" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="October" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="November" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="December" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element ref="{http://www.megatravel.com/xml-bsep}accommodation"/>
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pricePerMonth", propOrder = {
    "januar",
    "februar",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "accommodation",
    "year"
})
public class PricePerMonth {

    @XmlElement(name = "Januar")
    protected float januar;
    @XmlElement(name = "Februar")
    protected float februar;
    @XmlElement(name = "March")
    protected float march;
    @XmlElement(name = "April")
    protected float april;
    @XmlElement(name = "May")
    protected float may;
    @XmlElement(name = "June")
    protected float june;
    @XmlElement(name = "July")
    protected float july;
    @XmlElement(name = "August")
    protected float august;
    @XmlElement(name = "September")
    protected float september;
    @XmlElement(name = "October")
    protected float october;
    @XmlElement(name = "November")
    protected float november;
    @XmlElement(name = "December")
    protected float december;
    @XmlElement(required = true)
    protected Accommodation accommodation;
    @XmlElement(name = "Year", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;

    /**
     * Gets the value of the januar property.
     * 
     */
    public float getJanuar() {
        return januar;
    }

    /**
     * Sets the value of the januar property.
     * 
     */
    public void setJanuar(float value) {
        this.januar = value;
    }

    /**
     * Gets the value of the februar property.
     * 
     */
    public float getFebruar() {
        return februar;
    }

    /**
     * Sets the value of the februar property.
     * 
     */
    public void setFebruar(float value) {
        this.februar = value;
    }

    /**
     * Gets the value of the march property.
     * 
     */
    public float getMarch() {
        return march;
    }

    /**
     * Sets the value of the march property.
     * 
     */
    public void setMarch(float value) {
        this.march = value;
    }

    /**
     * Gets the value of the april property.
     * 
     */
    public float getApril() {
        return april;
    }

    /**
     * Sets the value of the april property.
     * 
     */
    public void setApril(float value) {
        this.april = value;
    }

    /**
     * Gets the value of the may property.
     * 
     */
    public float getMay() {
        return may;
    }

    /**
     * Sets the value of the may property.
     * 
     */
    public void setMay(float value) {
        this.may = value;
    }

    /**
     * Gets the value of the june property.
     * 
     */
    public float getJune() {
        return june;
    }

    /**
     * Sets the value of the june property.
     * 
     */
    public void setJune(float value) {
        this.june = value;
    }

    /**
     * Gets the value of the july property.
     * 
     */
    public float getJuly() {
        return july;
    }

    /**
     * Sets the value of the july property.
     * 
     */
    public void setJuly(float value) {
        this.july = value;
    }

    /**
     * Gets the value of the august property.
     * 
     */
    public float getAugust() {
        return august;
    }

    /**
     * Sets the value of the august property.
     * 
     */
    public void setAugust(float value) {
        this.august = value;
    }

    /**
     * Gets the value of the september property.
     * 
     */
    public float getSeptember() {
        return september;
    }

    /**
     * Sets the value of the september property.
     * 
     */
    public void setSeptember(float value) {
        this.september = value;
    }

    /**
     * Gets the value of the october property.
     * 
     */
    public float getOctober() {
        return october;
    }

    /**
     * Sets the value of the october property.
     * 
     */
    public void setOctober(float value) {
        this.october = value;
    }

    /**
     * Gets the value of the november property.
     * 
     */
    public float getNovember() {
        return november;
    }

    /**
     * Sets the value of the november property.
     * 
     */
    public void setNovember(float value) {
        this.november = value;
    }

    /**
     * Gets the value of the december property.
     * 
     */
    public float getDecember() {
        return december;
    }

    /**
     * Sets the value of the december property.
     * 
     */
    public void setDecember(float value) {
        this.december = value;
    }

    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYear(XMLGregorianCalendar value) {
        this.year = value;
    }

}
